steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/calculator-406120', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/calculator-406120']
# Deploy the container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'calculator-406120', '--image', 'gcr.io/$PROJECT_ID/calculator-406120', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
timeout: '1600s'
